import type { Comic } from "@/types/comic";
import { moods } from "@/design/comic-moods";

// PREVIEW ONLY: placeholder titles, copy and prices. Replace with final client material.
const d = (s: string) => s;
export const comics: Comic[] = [
  { slug: "negotiation", category: "work", outcomes: ["Listen for what each side needs, not only what they ask for", "Trade small concessions for things that matter more", "Stay calm and credible when the other side pushes back"], price: 199, title: "Negotiation", theme: "Negotiation", tags: ["Listening", "Trade-offs", "Win-win"], coverImage: "/characters/references/negotiation-cover.png", priceLabel: "₹199", videoAvailable: true, mood: moods.negotiation,
    shortDescription: d("Two sides, one table and a cat who wants a treat; watch how listening, patience and small trade-offs turn a stalemate into an agreement both sides can live with, then spot the same moves in everyday conversations at work and at home") },
  { slug: "ethics", category: "life", outcomes: ["Spot the moment a small shortcut becomes a real choice", "Weigh who is affected before you decide", "Act on your values even when nobody is watching"], price: 199, title: "Ethics", theme: "Ethics", tags: ["Choices", "Integrity", "Consequences"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.ethics,
    shortDescription: d("A small shortcut looks harmless until someone else pays for it; follow a character through a tough call and see how values, pressure and consequences meet when nobody is watching and the easy option is very tempting") },
  { slug: "resilience", category: "life", outcomes: ["Recognise a setback for what it is and what it is not", "Rest, rethink and try again with a smaller first step", "Build habits that make recovery faster next time"], price: 199, title: "Resilience", theme: "Resilience", tags: ["Setbacks", "Grit", "Recovery"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.resilience,
    shortDescription: d("Everything goes wrong on the same day; see how a character absorbs the blow, rests, rethinks the plan and tries again, and learn what bouncing back really looks like when it is slow, untidy and deeply human") },
  { slug: "emotional-intelligence", category: "life", outcomes: ["Name a feeling before it drives your reaction", "Read the mood of a room without guessing", "Respond to others with steadiness and care"], price: 199, title: "Emotional Intelligence", theme: "Emotional Intelligence", tags: ["Empathy", "Awareness", "Self-control"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.warm,
    shortDescription: d("A heated meeting, a quiet colleague and a message read the wrong way; notice how feelings shape choices, and how naming an emotion before reacting can change the conversation for everyone in the room") },
  { slug: "leadership", category: "work", outcomes: ["Earn trust through small and consistent actions", "Listen first when the plan falls apart", "Share credit and own the mistakes"], price: 199, title: "Leadership", theme: "Leadership", tags: ["Vision", "Trust", "Example"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.cinema,
    shortDescription: d("When the plan falls apart, people look up; follow a reluctant leader who learns that trust is built through small consistent actions, honest listening and the courage to share credit and take the blame") },
  { slug: "communication", category: "communication", outcomes: ["Say one thing clearly instead of five things loosely", "Ask questions that reveal what the other person heard", "Match your message to the person in front of you"], price: 199, title: "Communication", theme: "Communication", tags: ["Clarity", "Listening", "Feedback"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.bright,
    shortDescription: d("Same words, three different meanings; watch a simple request travel between people and get lost on the way, then see how clear framing, good questions and a moment of listening bring it safely home") },
  { slug: "persuasion", category: "work", outcomes: ["Build credibility before making the case", "Frame an idea so others feel invited", "Use stories and evidence together"], price: 199, title: "Persuasion", theme: "Persuasion", tags: ["Influence", "Stories", "Trust"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.warm,
    shortDescription: d("Facts alone rarely change a mind; see how a character earns attention, builds credibility and frames an idea so others feel invited rather than pushed, and why the best arguments feel like shared discoveries") },
  { slug: "decision-making", category: "work", outcomes: ["Set the options side by side before choosing", "Catch common biases in your own thinking", "Decide well enough to move forward"], price: 199, title: "Decision Making", theme: "Decision Making", tags: ["Judgement", "Bias", "Options"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.cinema,
    shortDescription: d("Two doors, limited time and too much advice; follow a character weighing options, catching their own biases and choosing well enough to move forward, without waiting for a perfect answer that never arrives") },
  { slug: "storytelling", category: "communication", outcomes: ["Give an idea a character and a problem", "Use a turning point to make it stick", "Cut everything that does not serve the story"], price: 199, title: "Storytelling", theme: "Storytelling", tags: ["Narrative", "Memory", "Connection"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.bright,
    shortDescription: d("Why do we forget slides but remember tales; watch a dull talk become a story people repeat, and learn how character, conflict and a clear turning point make an idea stay with its listeners for years") },
  { slug: "conflict-resolution", category: "life", outcomes: ["Separate the person from the problem", "Hear each side out before proposing a fix", "Find the shared interest underneath the argument"], price: 199, title: "Conflict Resolution", theme: "Conflict Resolution", tags: ["Mediation", "Respect", "Repair"], coverImage: "", priceLabel: "₹199", videoAvailable: true, mood: moods.ethics,
    shortDescription: d("Two friends stop talking over a small thing that is not small; see how separating people from problems, hearing each side out and finding shared interests can turn an argument into a repair") },
];

export const getComic = (slug: string) => comics.find((c) => c.slug === slug);
